# docker-compose.yml
services:
  web:
    build: .
    command: python /REST-example/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/REST-example
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgis/postgis:14-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
