# Generated by Django 5.0.4 on 2024-04-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='crs',
        ),
    ]
